import dynamic from 'next/dynamic';
import { Inter } from 'next/font/google';

import { AOSInit } from '@/components/website/common/AOSInit';
import AntdProvider from '@/components/website/common/AntdProvider';
import { FloatingButtons } from '@/components/website/common/FloatingButtons';

import './globals.css';
import './main.scss';

const Navbar = dynamic(() => {
	return import('../components/website/common/Navbar');
});

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Sirat-Al-Mustaqeem',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<AOSInit />

			<body className={inter.className}>
				<Navbar />
				<div className="relative">
					<FloatingButtons />
					<AntdProvider>{children}</AntdProvider>
				</div>
			</body>
		</html>
	);
}
